### ISSUE TITLE
Error when running on octave

### ISSUE THREAD

**Issue by dtrckd** [mingyuanzhou/EPM#1]
Hi,

I was able to compile and run the code under octave. Nevertheless, I have an exception raising for each model and crashing the execution with the following trace:

```octave
Treating Raw_Data as an Adj Matrix
h = -6.3352
W_Distr set to Normal (default)
E_Distr set to Bernoulli (default)
error: Raw Data is not an m by 3 Edge List\n
error: called from
    wsbm_driver>setup_Data at line 470 column 13
    wsbm_driver>format_input at line 163 column 9
    wsbm_driver at line 29 column 1
    wsbm at line 123 column 11
    WSBMDemo at line 24 column 8

```

Before the crash, suspicious values are the `m_i_k_dot_dot(:,i)` that has zero everywhere and  especially `p_ik_prime_one_minus` that has NaN everywhere.

Do you have any idea of what is going on how we can solve this ?

**Comment by mingyuanzhou** [comment]
Hi, sorry that the code was only tested under Matlab and not guaranteed to run under octave. There might be compatibility issue due to the use of mex c files to speed things up.
